// ═══════════════════════════════════════════════════════════════
// CAMERA BODIES — cinema camera body database
// Comprehensive cinematographer's reference — verified specs
// ═══════════════════════════════════════════════════════════════

export const cameraBodies = [
    {
        id: 'arri-alexa-35',
        name: 'ARRI ALEXA 35',
        manufacturer: 'ARRI',
        sensorWidth: 27.99,
        sensorHeight: 19.22,
        resolution: '4.6K (4608x3164)',
        nativeISO: '800 (160-6400)',
        claimedDR: 17,
        measuredDR: '15.1 SNR2',
        colorScience: 'ARRI REVEAL, LogC4, AWG4',
        colorTint: [1.03, 1.0, 0.95],
        viewfinderStyle: 'arri',
        lookSignature: 'natural film-like highlight rolloff, richest most accurate color, flatters all skin tones, organic film-like grain, warm-neutral filmic',
        feel: 'organic, filmic, gold-standard',
        description: 'S35 flagship with 17+ stops DR and ARRI REVEAL color science. The gold standard for color accuracy and highlight handling in modern cinema.',
        productions: 'Wicked, Killers of the Flower Moon, The Zone of Interest'
    },
    {
        id: 'arri-alexa-mini-lf',
        name: 'ARRI ALEXA Mini LF',
        manufacturer: 'ARRI',
        sensorWidth: 36.70,
        sensorHeight: 25.54,
        resolution: '4.5K (4448x3096)',
        nativeISO: '800',
        claimedDR: 14,
        measuredDR: '13.4 SNR2',
        colorScience: 'ARRI LogC3, REVEAL',
        colorTint: [1.03, 1.0, 0.95],
        viewfinderStyle: 'arri',
        lookSignature: 'organic ARRI color, large-format subject separation and depth, smooth rolloff, gentle skin',
        feel: 'organic, filmic, dimensional',
        description: 'Large format ARRI in a compact body. Organic color science with beautiful subject separation and shallow depth of field.',
        productions: 'The Batman, Dune'
    },
    {
        id: 'arri-alexa-65',
        name: 'ARRI ALEXA 65',
        manufacturer: 'ARRI',
        sensorWidth: 54.12,
        sensorHeight: 25.58,
        resolution: '6.5K (6560x3100)',
        nativeISO: '800 (200-3200)',
        claimedDR: 14,
        measuredDR: '~14',
        colorScience: 'ARRI LogC, REVEAL',
        colorTint: [1.03, 1.0, 0.95],
        viewfinderStyle: 'arri',
        lookSignature: 'ultimate large-format filmic, extreme resolution, huge subject separation, creamy falloff',
        feel: 'epic, dimensional, premium',
        description: 'The ultimate large-format cinema camera. 65mm sensor with ARRI color science for the most epic, dimensional imagery possible.',
        productions: 'The Revenant, Avengers Infinity War/Endgame, Dune Part Two'
    },
    {
        id: 'red-v-raptor-8k-vv',
        name: 'RED V-Raptor 8K VV',
        manufacturer: 'RED',
        sensorWidth: 40.96,
        sensorHeight: 21.60,
        resolution: '8K (8192x4320)',
        nativeISO: '800 (RAW)',
        claimedDR: 17,
        measuredDR: '12.8 SNR2',
        colorScience: 'RED IPP2, REDWideGamutRGB, Log3G10',
        colorTint: [0.98, 1.0, 1.04],
        viewfinderStyle: 'red',
        lookSignature: 'sharp modern flexible RAW, clean shadows, highlight recovery, neutral-cool gradable canvas',
        feel: 'clean, modern, flexible',
        description: 'VV sensor with 8K resolution and global shutter. Neutral-cool RAW canvas optimized for maximum post flexibility.',
        productions: 'Guardians of the Galaxy Vol. 3, Bullet Train'
    },
    {
        id: 'red-komodo-x',
        name: 'RED Komodo-X',
        manufacturer: 'RED',
        sensorWidth: 27.03,
        sensorHeight: 14.26,
        resolution: '6K (6144x3240)',
        nativeISO: '800',
        claimedDR: 16.5,
        measuredDR: '~13 SNR2',
        colorScience: 'RED IPP2',
        colorTint: [0.98, 1.0, 1.03],
        viewfinderStyle: 'red',
        lookSignature: 'compact RED, global-shutter clean, good color/shadows, flexible crossover cam',
        feel: 'clean, modern, versatile',
        description: 'Compact S35 cinema camera with global shutter and RED IPP2 color. Versatile crossover between cinema and run-and-gun.',
        productions: 'Babylon, Dont Look Up (Atlas Orions on similar bodies)'
    },
    {
        id: 'sony-venice-2',
        name: 'Sony Venice 2 (8.6K)',
        manufacturer: 'Sony',
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        resolution: '8.6K (8640x5760)',
        nativeISO: 'dual 800/3200',
        claimedDR: 16,
        measuredDR: '~14 SNR2',
        colorScience: 'Sony S-Gamut3.Cine, S-Log3, S-Cinetone',
        colorTint: [1.01, 1.01, 0.99],
        viewfinderStyle: 'sony',
        lookSignature: 'natural skin tones, excellent color separation, clean slightly warm, premium low-light, modern blockbuster look',
        feel: 'clean, premium, cinematic',
        description: 'Full-frame dual-base ISO cinema camera with 8.6K sensor. Excellent color separation and premium low-light performance.',
        productions: 'Top Gun Maverick, Black Panther Wakanda Forever, The Crown'
    },
    {
        id: 'sony-fx3',
        name: 'Sony FX3',
        manufacturer: 'Sony',
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        resolution: 'UHD 4K (12.1MP full frame)',
        nativeISO: 'dual 640/12800',
        claimedDR: 15,
        measuredDR: '~13 SNR2',
        colorScience: 'Sony S-Cinetone, S-Log3',
        colorTint: [1.01, 1.01, 0.99],
        viewfinderStyle: 'sony',
        lookSignature: 'exceptional low-light, S-Cinetone film-like color, rich skin tones, clean slightly warm, Venice-derived',
        feel: 'clean, cinematic, low-light king',
        description: 'Full-frame cinema line camera with Venice-derived color science. Exceptional low-light and S-Cinetone for film-like rendering.',
        productions: 'Documentary and indie cinema'
    },
    {
        id: 'blackmagic-ursa-cine-12k-lf',
        name: 'Blackmagic URSA Cine 12K LF',
        manufacturer: 'Blackmagic Design',
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        resolution: '12K (12288x8040) RGBW',
        nativeISO: '800',
        claimedDR: 16,
        measuredDR: '~13 SNR2',
        colorScience: 'Blackmagic Gen 5 Color',
        colorTint: [1.0, 1.0, 1.0],
        viewfinderStyle: 'blackmagic',
        lookSignature: 'nuanced skin tones, natural rolloff, clean shadows, large-format depth, filmic value',
        feel: 'organic, large-format, value-premium',
        description: 'Large-format 12K RGBW cinema camera with Gen 5 color science. Nuanced skin tones and natural rolloff at an accessible price.',
        productions: 'Indie cinema and commercial'
    },
    {
        id: 'blackmagic-ursa-mini-pro-12k',
        name: 'Blackmagic URSA Mini Pro 12K',
        manufacturer: 'Blackmagic Design',
        sensorWidth: 27.03,
        sensorHeight: 14.26,
        resolution: '12K (12288x6480) S35 RGBW 80MP',
        nativeISO: '800',
        claimedDR: 14,
        measuredDR: '~13 SNR2',
        colorScience: 'Blackmagic Gen 5 Color',
        colorTint: [1.0, 1.0, 1.0],
        viewfinderStyle: 'blackmagic',
        lookSignature: 'extremely detailed S35, oversampled subtle skin tones, sharp without harsh edges',
        feel: 'detailed, clean, flexible',
        description: 'S35 12K RGBW cinema camera. Extreme resolution oversamples for subtle skin tones and sharp-but-smooth detail.',
        productions: 'Indie cinema and VFX plates'
    },
    {
        id: 'blackmagic-pocket-6k-pro',
        name: 'Blackmagic Pocket 6K Pro',
        manufacturer: 'Blackmagic Design',
        sensorWidth: 23.10,
        sensorHeight: 12.99,
        resolution: '6K (6144x3456)',
        nativeISO: 'dual 400/3200',
        claimedDR: 13,
        measuredDR: '~12 SNR2',
        colorScience: 'Blackmagic Gen 5 Color',
        colorTint: [1.0, 1.0, 1.0],
        viewfinderStyle: 'blackmagic',
        lookSignature: 'organic Gen 5 color, pleasing skin, natural rolloff, S35 depth, filmic value but disciplined exposure',
        feel: 'organic, value-filmic',
        description: 'S35 cinema camera with EF mount and built-in ND. Nuts own camera.',
        productions: 'Indie cinema, short films, YouTube'
    },
    {
        id: 'imax-msm-9802',
        name: 'IMAX MSM 9802',
        manufacturer: 'IMAX',
        sensorWidth: 69.60,
        sensorHeight: 48.59,
        resolution: '~18K equivalent (15-perf 65mm film)',
        nativeISO: 'film stock dependent',
        claimedDR: 14,
        measuredDR: '~13-15 stops film latitude',
        colorScience: 'IMAX / Kodak film',
        colorTint: [1.0, 1.0, 1.0],
        viewfinderStyle: 'imax',
        lookSignature: 'unmatched resolution and scale, epic large-canvas, immense separation, organic film grain and rolloff',
        feel: 'epic, monumental, photochemical',
        description: '70mm 15-perf IMAX format. The largest cinema capture format in existence, with unmatched resolution and immersive scale.',
        productions: 'Oppenheimer, Dunkirk, Interstellar, The Dark Knight'
    },
    {
        id: 'panavision-dxl2',
        name: 'Panavision DXL2',
        manufacturer: 'Panavision',
        sensorWidth: 40.96,
        sensorHeight: 21.60,
        resolution: '8K (8192x4320)',
        nativeISO: '1600',
        claimedDR: 16,
        measuredDR: '~13 SNR2',
        colorScience: 'Light Iron Color 2 over RED IPP2',
        colorTint: [1.02, 1.0, 0.97],
        viewfinderStyle: 'panavision',
        lookSignature: 'film-like density, neutral shadows, natural skin, classic Panavision large-format signature',
        feel: 'filmic, premium, large-format',
        description: 'Large format camera built on RED Monstro sensor with Light Iron Color 2 pipeline. Film-like density tuned for Panavision glass.',
        productions: 'Venom, A Quiet Place Part II'
    },
    {
        id: 'canon-c500-ii',
        name: 'Canon C500 Mark II',
        manufacturer: 'Canon',
        sensorWidth: 38.1,
        sensorHeight: 20.1,
        resolution: '5.9K (5952x3140)',
        nativeISO: '800',
        claimedDR: 15,
        measuredDR: '13.1 SNR2',
        colorScience: 'Canon Cinema Gamut, C-Log2/3',
        colorTint: [1.02, 1.0, 0.98],
        viewfinderStyle: 'canon',
        lookSignature: 'smooth natural flattering skin tones, warm-pleasing, clean, reliable Canon color',
        feel: 'natural, warm, easy',
        description: 'Full-frame cinema camera with excellent autofocus and reliable Canon color science. Smooth, flattering skin tones out of the box.',
        productions: 'Documentary, commercial, indie'
    },
    {
        id: 'blackmagic-cinema-6k',
        name: 'Blackmagic Cinema Camera 6K',
        manufacturer: 'Blackmagic Design',
        sensorWidth: 24.89,
        sensorHeight: 18.67,
        resolution: '6K (6048x4032)',
        nativeISO: 'dual 400/3200',
        claimedDR: 13,
        measuredDR: '~12 SNR2',
        colorScience: 'Blackmagic Gen 5 Color',
        colorTint: [1.0, 1.0, 1.0],
        viewfinderStyle: 'blackmagic',
        lookSignature: 'full-frame L-mount cinema camera, Blackmagic RAW, Gen 5 color',
        feel: 'modern, accessible',
        description: 'Full-frame 6K cinema camera with L-mount. Blackmagic RAW and Gen 5 color science in an accessible package.',
        productions: 'Indie cinema, commercial'
    }
];

export function getBody(id) {
    return cameraBodies.find(b => b.id === id) || cameraBodies[0];
}

export function fovForBody(body, focalLength) {
    return 2 * Math.atan((body.sensorHeight / 2) / focalLength) * (180 / Math.PI);
}
